# Generated by Django 5.2.17 on 2026-09-21 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('unreviewed', '待核'), ('grouped', '已确认归一'), ('independent', '已确认独立')], db_default='unreviewed', default='unreviewed', max_length=16, verbose_name='状态')),
                ('needs_info', models.BooleanField(default=False, verbose_name='待补充')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='待补充字段')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '归一产品',
                'verbose_name_plural': '归一产品',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('pair', '疑似同一产品'), ('incomplete', '待补充'), ('key_change', '关键字段变化')], max_length=16, verbose_name='类型')),
                ('category', models.CharField(choices=[('strong', '强证据疑似同一产品'), ('no_number', '无编号佐证'), ('same_source', '同源重复'), ('number_conflict', '编号冲突'), ('position_conflict', '位置冲突'), ('spec_conflict', '规格冲突'), ('insufficient', '信息不足'), ('incomplete', '待补充'), ('key_change', '关键字段变化')], max_length=20, verbose_name='类别')),
                ('strength', models.CharField(max_length=10, verbose_name='强度')),
                ('identity_a', models.CharField(max_length=220, verbose_name='身份 A')),
                ('identity_b', models.CharField(blank=True, max_length=220, verbose_name='身份 B')),
                ('triggers', models.JSONField(default=list, verbose_name='触发原因')),
                ('agreements', models.JSONField(default=list, verbose_name='一致字段')),
                ('conflicts', models.JSONField(default=list, verbose_name='冲突字段')),
                ('missing', models.JSONField(default=list, verbose_name='缺失字段')),
                ('suggested_action', models.TextField(verbose_name='建议动作')),
                ('evidence_hash', models.CharField(max_length=64, verbose_name='证据哈希')),
                ('rules_version', models.CharField(max_length=40, verbose_name='规则版本')),
                ('status', models.CharField(choices=[('open', '未决'), ('same', '确认同一'), ('different', '判为不同'), ('independent', '确认独立'), ('needs_info', '待补充'), ('superseded', '证据已变化')], default='open', max_length=16, verbose_name='状态')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='决定时间')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='决定人')),
                ('record_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sources.sourcerecord', verbose_name='记录 A')),
                ('record_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sources.sourcerecord', verbose_name='记录 B')),
            ],
            options={
                'verbose_name': '待确认条目',
                'verbose_name_plural': '待确认条目',
                'ordering': ['status', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40, verbose_name='动作')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('payload', models.JSONField(default=dict, verbose_name='内容')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='archive.reviewitem')),
            ],
            options={
                'verbose_name': '决策日志',
                'verbose_name_plural': '决策日志',
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('record_key', models.CharField(max_length=200, verbose_name='记录身份')),
                ('status', models.CharField(choices=[('active', '有效'), ('suspended', '暂停（关键字段变化，待复核）')], default='active', max_length=16, verbose_name='状态')),
                ('current_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='sources.sourcerecord', verbose_name='当前版本')),
                ('joined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='suppliers.supplier', verbose_name='供应商')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='archive.product', verbose_name='归一产品')),
            ],
            options={
                'verbose_name': '归一成员',
                'verbose_name_plural': '归一成员',
                'constraints': [models.UniqueConstraint(fields=('supplier', 'record_key'), name='archive_one_membership_per_identity')],
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('field', models.CharField(max_length=40, verbose_name='字段')),
                ('value', models.JSONField(verbose_name='取值')),
                ('reason', models.TextField(verbose_name='依据')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sources.sourcerecord', verbose_name='取值来源')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='archive.product')),
            ],
            options={
                'verbose_name': '字段取值决定',
                'verbose_name_plural': '字段取值决定',
                'constraints': [models.UniqueConstraint(fields=('product', 'field'), name='archive_one_choice_per_field')],
            },
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['kind', 'identity_a', 'identity_b'], name='archive_item_pair'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('kind', 'identity_a', 'identity_b'), name='archive_one_open_item'),
        ),
    ]
