# Generated by Django 5.2.17 on 2026-09-22 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='合并后保留编号，指向接收它的产品', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absorbed', to='archive.product', verbose_name='并入'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('unreviewed', '待核'), ('grouped', '已确认归一'), ('independent', '已确认独立'), ('merged', '已并入其他产品')], db_default='unreviewed', default='unreviewed', max_length=16, verbose_name='状态'),
        ),
    ]
