# Generated by Django 5.2.17 on 2026-09-18 07:19

import apps.inquiries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_suggestions'),
        ('catalog', '0002_listing_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('input_type', models.CharField(choices=[('text', '文字'), ('image', '图片')], max_length=8, verbose_name='输入类型')),
                ('raw_input', models.TextField(blank=True, help_text='文字询价的原文；图片询价为空', verbose_name='原始输入')),
                ('image', models.ImageField(blank=True, upload_to=apps.inquiries.models.inquiry_image_upload_to, verbose_name='照片')),
                ('finding', models.JSONField(blank=True, default=dict, help_text='AI 读图结果与候选列表；候选只是建议，确认后才写 matched_part', verbose_name='识别结果')),
                ('status', models.CharField(choices=[('open', '待确认'), ('matched', '已确认产品'), ('quoted', '已报价')], db_default='open', default='open', max_length=16, verbose_name='状态')),
                ('customer', models.CharField(blank=True, max_length=200, verbose_name='客户')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('ai_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aitask', verbose_name='AI 调用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='询价人')),
                ('matched_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.part', verbose_name='确认的产品')),
            ],
            options={
                'verbose_name': '询价',
                'verbose_name_plural': '询价',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inquiries_recent'), models.Index(fields=['matched_part'], name='inquiries_matched_part')],
            },
        ),
    ]
