# Generated by Django 5.2.17 on 2026-09-18 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_suggestions'),
        ('catalog', '0002_listing_content'),
        ('inquiries', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qty', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_cost_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单位成本 USD')),
                ('margin', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='毛利率')),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价 USD')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '报价行',
                'verbose_name_plural': '报价行',
                'ordering': ['inquiry', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='query_key',
            field=models.CharField(blank=True, db_index=True, help_text='归一化后的输入，用来统计同一个号的不同写法', max_length=200, verbose_name='查询键'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['created_by', 'input_type', 'created_at'], name='inquiries_user_type_time'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='inquiries.inquiry', verbose_name='询价'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='suppliers.supplieroffer', verbose_name='成本来源报价'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.part', verbose_name='产品'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='inquiries_quote_qty_positive'),
        ),
    ]
