# Generated by Django 5.2.17 on 2026-09-18 04:43

import apps.importer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(upload_to=apps.importer.models.import_upload_to, verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('mapped', '已映射'), ('validated', '已预检'), ('importing', '导入中'), ('done', '已完成'), ('failed', '失败')], db_default='uploaded', default='uploaded', max_length=16, verbose_name='状态')),
                ('header_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='表头所在行')),
                ('column_mapping', models.JSONField(blank=True, db_default={}, default=dict, verbose_name='列映射')),
                ('stats', models.JSONField(blank=True, db_default={}, default=dict, verbose_name='统计')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(verbose_name='表格行号')),
                ('raw', models.JSONField(default=dict, verbose_name='原始值')),
                ('result', models.CharField(choices=[('new', '新增'), ('updated', '更新'), ('skipped', '跳过'), ('duplicate', '疑似重复'), ('invalid', '无效')], max_length=16, verbose_name='结果')),
                ('message', models.TextField(blank=True, verbose_name='说明')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importer.importbatch')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.part', verbose_name='产品')),
            ],
            options={
                'verbose_name': '导入行',
                'verbose_name_plural': '导入行',
                'ordering': ['batch', 'row_no'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_no'), name='importer_row_unique_per_batch')],
            },
        ),
    ]
