# Generated by Django 5.2.17 on 2026-09-18 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_trigram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(max_length=32, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='说明')),
                ('task_id', models.CharField(blank=True, max_length=64, verbose_name='django-q 任务 ID')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('done', '已完成'), ('failed', '失败')], default='queued', max_length=16, verbose_name='状态')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='总数')),
                ('done', models.PositiveIntegerField(default=0, verbose_name='已完成')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='失败')),
                ('message', models.TextField(blank=True, verbose_name='说明')),
                ('result_url', models.CharField(blank=True, max_length=200, verbose_name='结果页')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '后台任务',
                'verbose_name_plural': '后台任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
