# Generated by Django 5.2.17 on 2026-09-18 04:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('country', models.CharField(blank=True, default='China', max_length=50, verbose_name='国家')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='联系方式')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5，5 为最好', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评级')),
                ('notes', models.TextField(blank=True, help_text='产品线、质量记录等', verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='suppliers_supplier_rating_1_5')],
            },
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier_pn', models.CharField(blank=True, max_length=64, verbose_name='供应商料号')),
                ('unit_cost_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价 USD')),
                ('moq', models.PositiveIntegerField(blank=True, null=True, verbose_name='起订量')),
                ('lead_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='交期（天）')),
                ('price_term', models.CharField(choices=[('EXW', 'EXW 工厂交货'), ('FOB', 'FOB 离岸价'), ('CIF', 'CIF 到岸价')], default='FOB', max_length=3, verbose_name='价格条款')),
                ('quoted_at', models.DateField(verbose_name='报价日期')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('notes', models.TextField(blank=True, help_text='原币种与汇率、质量记录等', verbose_name='备注')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.part', verbose_name='产品')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商报价',
                'verbose_name_plural': '供应商报价',
                'ordering': ['unit_cost_usd', 'lead_days', 'id'],
                'indexes': [models.Index(fields=['part', 'unit_cost_usd'], name='suppliers_offer_part_cost')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'part', 'quoted_at'), name='suppliers_offer_unique_per_day'), models.CheckConstraint(condition=models.Q(('unit_cost_usd__gt', Decimal('0'))), name='suppliers_offer_cost_positive'), models.CheckConstraint(condition=models.Q(('moq__isnull', True), ('moq__gt', 0), _connector='OR'), name='suppliers_offer_moq_positive'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('quoted_at')), _connector='OR'), name='suppliers_offer_valid_after_quote')],
            },
        ),
    ]
