# Generated by Django 5.2.17 on 2026-09-21 15:51

import apps.sources.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(upload_to=apps.sources.models.source_upload_to, verbose_name='原件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='大小（字节）')),
                ('file_format', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=8, verbose_name='格式')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('mapped', '已确认映射'), ('previewed', '已预检'), ('committed', '已入库'), ('failed', '解析失败')], db_default='uploaded', default='uploaded', max_length=16, verbose_name='状态')),
                ('mapping', models.JSONField(blank=True, db_default={}, default=dict, verbose_name='列映射')),
                ('stats', models.JSONField(blank=True, db_default={}, default=dict, verbose_name='统计')),
                ('error', models.TextField(blank=True, verbose_name='失败原因')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_files', to='suppliers.supplier', verbose_name='供应商')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '资料文件',
                'verbose_name_plural': '资料文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_key', models.CharField(help_text='同一供应商内识别"同一条记录"的键', max_length=200, verbose_name='记录身份')),
                ('key_kind', models.CharField(choices=[('source_id', '源记录 ID'), ('supplier_sku', '供应商料号'), ('content', '内容哈希（无稳定键）')], max_length=16, verbose_name='身份来源')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('change_type', models.CharField(choices=[('new', '新增'), ('price_update', '报价更新'), ('key_change', '关键字段变化')], default='new', max_length=16, verbose_name='变化类型')),
                ('locator', models.CharField(help_text='如 Sheet1!R12 或 P3/T1/R5', max_length=120, verbose_name='定位')),
                ('sheet', models.CharField(blank=True, max_length=100, verbose_name='工作表')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='页码')),
                ('table_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='表序号')),
                ('row_no', models.PositiveIntegerField(verbose_name='行号')),
                ('raw', models.JSONField(default=dict, help_text='原表头 → 单元格原文', verbose_name='原文')),
                ('cells', models.JSONField(default=dict, help_text='原表头 → 单元格坐标', verbose_name='单元格')),
                ('fields', models.JSONField(default=dict, help_text='字段 → 值、原文、列、单元格、规则、警告', verbose_name='标准字段')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='警告')),
                ('missing', models.JSONField(blank=True, default=list, verbose_name='缺失字段')),
                ('content_hash', models.CharField(max_length=64, verbose_name='内容哈希')),
                ('supplier_sku', models.CharField(blank=True, max_length=100, verbose_name='供应商料号')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='原始名称')),
                ('part_type', models.CharField(blank=True, max_length=100, verbose_name='品类')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='位置')),
                ('make', models.CharField(blank=True, max_length=60, verbose_name='适配品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='适配车型')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='起始年份')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='截止年份')),
                ('dim_l_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='长 cm')),
                ('dim_w_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='宽 cm')),
                ('dim_h_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='高 cm')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='单价')),
                ('currency', models.CharField(blank=True, help_text='原样保留，不换算', max_length=3, verbose_name='币种')),
                ('moq', models.PositiveIntegerField(blank=True, null=True, verbose_name='MOQ')),
                ('quote_date', models.DateField(blank=True, null=True, verbose_name='报价日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='写入时间')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='sources.sourcerecord', verbose_name='上一版本')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='sources.sourcefile', verbose_name='资料文件')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_records', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '来源记录',
                'verbose_name_plural': '来源记录',
                'ordering': ['source_file', 'row_no'],
            },
        ),
        migrations.CreateModel(
            name='RecordNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('supplier_sku', '供应商料号'), ('oe', 'OE / 互换号'), ('source_id', '源记录 ID')], max_length=16, verbose_name='类型')),
                ('number', models.CharField(max_length=100, verbose_name='编号原文')),
                ('number_norm', models.CharField(db_index=True, editable=False, max_length=100, verbose_name='归一化编号')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='sources.sourcerecord', verbose_name='来源记录')),
            ],
            options={
                'verbose_name': '来源编号',
                'verbose_name_plural': '来源编号',
            },
        ),
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('header_signature', models.CharField(max_length=64, verbose_name='表头签名')),
                ('headers', models.JSONField(default=list, verbose_name='表头')),
                ('columns', models.JSONField(default=list, verbose_name='列映射')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '列映射模板',
                'verbose_name_plural': '列映射模板',
                'constraints': [models.UniqueConstraint(fields=('supplier', 'header_signature'), name='sources_template_unique_per_supplier')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcefile',
            constraint=models.UniqueConstraint(fields=('supplier', 'sha256'), name='sources_file_unique_per_supplier'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['supplier', 'record_key'], name='sources_record_identity'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['part_type', 'make', 'model'], name='sources_record_block'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('source_file', 'locator'), name='sources_record_unique_locator'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.CheckConstraint(condition=models.Q(('previous__isnull', True), ('version__gt', 1), _connector='OR'), name='sources_record_version_after_first'),
        ),
        migrations.AddConstraint(
            model_name='recordnumber',
            constraint=models.UniqueConstraint(fields=('record', 'kind', 'number_norm'), name='sources_number_unique_per_record'),
        ),
        migrations.AddConstraint(
            model_name='recordnumber',
            constraint=models.CheckConstraint(condition=models.Q(('number_norm', ''), _negated=True), name='sources_number_norm_not_empty'),
        ),
    ]
