# Generated by Django 5.2.17 on 2026-09-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerecord',
            name='change_type',
            field=models.CharField(choices=[('new', '新增'), ('price_update', '报价更新'), ('info_update', '资料更新（非关键字段）'), ('key_change', '关键字段变化')], default='new', max_length=16, verbose_name='变化类型'),
        ),
    ]
