# Generated by Django 5.2.17 on 2026-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_change_type_info_update'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sourcerecord',
            name='sources_record_unique_locator',
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='note',
            field=models.CharField(blank=True, help_text='规则重算时记下规则版本与变化字段', max_length=200, verbose_name='版本说明'),
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='change_type',
            field=models.CharField(choices=[('new', '新增'), ('price_update', '报价更新'), ('info_update', '资料更新（非关键字段）'), ('key_change', '关键字段变化'), ('restandardize', '规则重算')], default='new', max_length=16, verbose_name='变化类型'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('source_file', 'locator', 'version'), name='sources_record_unique_locator'),
        ),
    ]
