# Generated by Django 5.2.17 on 2026-09-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prompt_name', models.CharField(db_index=True, max_length=64, verbose_name='提示词')),
                ('provider', models.CharField(max_length=32, verbose_name='提供商')),
                ('model', models.CharField(max_length=100, verbose_name='模型')),
                ('input_digest', models.CharField(help_text='sha256 前 16 位', max_length=16, verbose_name='输入摘要')),
                ('input_preview', models.CharField(blank=True, max_length=500, verbose_name='输入预览')),
                ('has_image', models.BooleanField(default=False, verbose_name='含图片')),
                ('output', models.TextField(blank=True, verbose_name='输出')),
                ('status', models.CharField(choices=[('ok', '成功'), ('invalid_json', '输出无法解析'), ('error', '调用失败')], max_length=16, verbose_name='状态')),
                ('error', models.TextField(blank=True, verbose_name='错误')),
                ('attempts', models.PositiveSmallIntegerField(default=1, verbose_name='尝试次数')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='输入 tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='输出 tokens')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='耗时 ms')),
            ],
            options={
                'verbose_name': 'AI 调用记录',
                'verbose_name_plural': 'AI 调用记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ai_task_status_recent')],
            },
        ),
    ]
