# Generated by Django 5.2.17 on 2026-09-18 05:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('catalog', '0002_listing_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payload', models.JSONField(verbose_name='建议内容')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已采纳'), ('rejected', '已拒绝')], db_default='pending', default='pending', max_length=16, verbose_name='状态')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, verbose_name='置信度')),
                ('accepted_fields', models.JSONField(blank=True, default=list, verbose_name='采纳的字段')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reason', models.TextField(blank=True, verbose_name='拒绝原因 / 审核说明')),
                ('ai_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='ai.aitask', verbose_name='AI 调用')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='catalog.part', verbose_name='产品')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': 'AI 建议',
                'verbose_name_plural': 'AI 建议',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ai_suggestion_queue')],
            },
        ),
    ]
