# Generated by Django 5.2.17 on 2026-09-18 03:37

import apps.catalog.models
import apps.core.operations
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_trigram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='品牌')),
                ('kind', models.CharField(choices=[('oem', '整车 / 主机厂'), ('aftermarket', '零部件品牌')], default='oem', max_length=16, verbose_name='类型')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_brand_unique_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名')),
                ('code', models.CharField(blank=True, help_text='如 BRK，用于生成 SKU', max_length=8, verbose_name='SKU 代码')),
                ('attribute_schema', models.JSONField(blank=True, db_default={}, default=dict, verbose_name='属性定义')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('manual', '人工'), ('import', '导入'), ('ai', 'AI')], db_default='manual', default='manual', max_length=16, verbose_name='来源')),
                ('confidence', models.DecimalField(db_default=Decimal('1.00'), decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='置信度')),
                ('verified', models.BooleanField(db_default=False, default=False, verbose_name='已人工确认')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文品名')),
                ('name_zh', models.CharField(blank=True, max_length=200, verbose_name='中文品名')),
                ('attributes', models.JSONField(blank=True, db_default={}, default=dict, verbose_name='规格属性')),
                ('description_en', models.TextField(blank=True, verbose_name='英文描述')),
                ('keywords', models.JSONField(blank=True, db_default=[], default=list, verbose_name='关键词')),
                ('packaging', models.JSONField(blank=True, db_default={}, default=dict, verbose_name='包装')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('reviewed', '已审核'), ('published', '已上架')], db_default='draft', default='draft', max_length=16, verbose_name='状态')),
                ('completeness_score', models.PositiveSmallIntegerField(db_default=0, default=0, verbose_name='完整度')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='catalog.category', verbose_name='分类')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['sku'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('manual', '人工'), ('import', '导入'), ('ai', 'AI')], db_default='manual', default='manual', max_length=16, verbose_name='来源')),
                ('confidence', models.DecimalField(db_default=Decimal('1.00'), decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='置信度')),
                ('verified', models.BooleanField(db_default=False, default=False, verbose_name='已人工确认')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('make', models.CharField(max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='车系')),
                ('engine', models.CharField(blank=True, max_length=50, verbose_name='发动机')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='起始年份')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='截止年份')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.part', verbose_name='产品')),
            ],
            options={
                'verbose_name': '适配车型',
                'verbose_name_plural': '适配车型',
                'ordering': ['make', 'model', 'year_from'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('manual', '人工'), ('import', '导入'), ('ai', 'AI')], db_default='manual', default='manual', max_length=16, verbose_name='来源')),
                ('confidence', models.DecimalField(db_default=Decimal('1.00'), decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='置信度')),
                ('verified', models.BooleanField(db_default=False, default=False, verbose_name='已人工确认')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('image', models.ImageField(upload_to=apps.catalog.models.part_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='图片')),
                ('is_primary', models.BooleanField(db_default=False, default=False, verbose_name='主图')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.part', verbose_name='产品')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['-is_primary', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('manual', '人工'), ('import', '导入'), ('ai', 'AI')], db_default='manual', default='manual', max_length=16, verbose_name='来源')),
                ('confidence', models.DecimalField(db_default=Decimal('1.00'), decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='置信度')),
                ('verified', models.BooleanField(db_default=False, default=False, verbose_name='已人工确认')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('number', models.CharField(max_length=64, verbose_name='编号原文')),
                ('number_norm', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='归一化编号')),
                ('kind', models.CharField(choices=[('OE', '原厂号 OE'), ('CROSS', '互换号 Cross'), ('SUPPLIER', '供应商料号')], max_length=16, verbose_name='类型')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='catalog.brand', verbose_name='编号品牌')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='catalog.part', verbose_name='产品')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '编号',
                'verbose_name_plural': '编号',
                'ordering': ['kind', 'number_norm'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce('parent', 0), models.F('name'), name='catalog_category_unique_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['status', 'completeness_score'], name='catalog_part_status_score'),
        ),
        apps.core.operations.PostgresOnlyAddIndex(
            model_name='part',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='catalog_part_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='catalog_part_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('completeness_score__lte', 100)), name='catalog_part_score_max_100'),
        ),
        migrations.AddIndex(
            model_name='fitment',
            index=models.Index(fields=['make', 'model'], name='catalog_fitment_make_model'),
        ),
        migrations.AddConstraint(
            model_name='fitment',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='catalog_fitment_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='fitment',
            constraint=models.UniqueConstraint(models.F('part'), django.db.models.functions.text.Lower('make'), django.db.models.functions.text.Lower('model'), django.db.models.functions.text.Lower('engine'), django.db.models.functions.comparison.Coalesce('year_from', 0), django.db.models.functions.comparison.Coalesce('year_to', 0), name='catalog_fitment_unique'),
        ),
        migrations.AddConstraint(
            model_name='fitment',
            constraint=models.CheckConstraint(condition=models.Q(('year_from__isnull', True), ('year_to__isnull', True), ('year_to__gte', models.F('year_from')), _connector='OR'), name='catalog_fitment_year_order'),
        ),
        migrations.AddConstraint(
            model_name='partimage',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='catalog_partimage_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='partimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('part',), name='catalog_image_one_primary'),
        ),
        apps.core.operations.PostgresOnlyAddIndex(
            model_name='partnumber',
            index=django.contrib.postgres.indexes.GinIndex(fields=['number_norm'], name='catalog_pn_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='catalog_partnumber_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', False)), fields=('part', 'number_norm', 'kind', 'brand'), name='catalog_pn_unique_per_part_brand'),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('part', 'number_norm', 'kind'), name='catalog_pn_unique_per_part_nobrand'),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.CheckConstraint(condition=models.Q(('number_norm', ''), _negated=True), name='catalog_pn_norm_not_empty'),
        ),
    ]
