# Generated by Django 5.2.17 on 2026-09-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='faq',
            field=models.JSONField(blank=True, db_default=[], default=list, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='part',
            name='selling_points',
            field=models.JSONField(blank=True, db_default=[], default=list, verbose_name='卖点'),
        ),
        migrations.AddField(
            model_name='part',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='上架标题'),
        ),
    ]
